Update to 2021.2 EAP
architectury/architectury-idea-plugin pull request #10
Opened 2021-06-02 16:08 UTC by ThexXTURBOXx

Basic functionality seems to work :)

2021-06-02 16:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/architectury/architectury-idea-plugin?pullRequest=10) <br/>All committers have signed the CLA.

2021-06-02 16:11 UTC, Juuxel requested changes
Thanks for this PR! I can merge it once 2021.2 gets a stable release, since maintaining two separate branches needs some more work.

2021-06-02 16:11 UTC, Juuxel commented on build.gradle.kts
> +    plugins.set("java, Kotlin".split(',').map(String::trim))
```suggestion
    plugins.set(listOf("java", "Kotlin"))
```

2021-06-02 16:11 UTC, Juuxel commented on build.gradle.kts
> +    kotlin("jvm") version "1.4.32" // Corresponds to IDEA 2021.2 EAP, see kt jars inside the ideaIC dep in IDEA
Just making sure, did you check this? They might have updated to Kotlin 1.5.

2021-06-02 16:40 UTC, ThexXTURBOXx commented on build.gradle.kts
> +    kotlin("jvm") version "1.4.32" // Corresponds to IDEA 2021.2 EAP, see kt jars inside the ideaIC dep in IDEA
I checked that and it seems like they are using 1.4 still. I will, however, check again!

2021-06-02 16:47 UTC, ThexXTURBOXx commented on build.gradle.kts
> +    kotlin("jvm") version "1.4.32" // Corresponds to IDEA 2021.2 EAP, see kt jars inside the ideaIC dep in IDEA
Checked again, they are still using 1.4.32 for now. If they update it in another EAP version (I don't believe they would...), I will update my PR accordingly

2021-06-02 16:49 UTC, ThexXTURBOXx commented
> 
> 
> Thanks for this PR! I can merge it once 2021.2 gets a stable release, since maintaining two separate branches needs some more work.

Yes, no problem! Does your license allow me to upload a 2021.2 EAP version of your plugin to my webspace and link to it here for other users?

2021-06-02 16:54 UTC, Juuxel commented
It does, as long as you follow its other terms. Also for now, I think I can somehow update the version range so that the current version built on 2021.1 also works on 2021.2 EAP.

2021-06-02 16:57 UTC, ThexXTURBOXx commented
Okay perfect. Then I will read through them later, thanks!
I could also adjust this PR such that 2021.2 EAP is supported next to 2021.1, if you want.

2021-06-03 09:13 UTC, ThexXTURBOXx commented
Now the plugin should support both at the same time

2021-06-09 07:11 UTC, Juuxel approved these changes

2021-06-09 07:15 UTC, merged

2021-06-09 07:15 UTC, Juuxel commented
Thanks for the update! I'll probably change this locally to build on 2021.1 still, but future releases should support 2021.2 too.